spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://116.62.42.225:3306/smartRec_?characterEncoding=utf8&useSSL=true
    username: ekoo
    password: ekoo2017
#spring:
#  jpa:
#    show-sql: true
#  datasource:
#    url: jdbc:mysql://202.75.214.41:3306/smartRec?characterEncoding=utf8&useSSL=true
#    username: ekoo
#    password: ekoo2017
wx_config:
    app_id: wx0afea86268a2d20b
    secret: d11b68fff3711d3badb3b5f82f182791
    redirectUrl: http://m.myhuipin.com/wxTest/
#sms:
#  config:
#    agent-url: http://218.244.136.70:8888/sms.aspx
#    sender-id: 3416
#    sender-account: 云装助手
#    sender-password: iUaJWLd534tp
#    signature: 【银雀科技】
#    open: false
a_li_sms_sender:
    accessKeyID: "LTAIuVaCEVgx6hiV"
    accessKeySecret: "mEJHdoKLq92v091e4OOPIu7i0JHn0h"
    signName: "慧聘"
    open: true
easemob:
    protocal: https
    host: a1.easemob.com
    org: 1152161118178178
    app: huipin
    client-id: YXA6g_LVoLxkEea_HMcpYdHLWA
    client-secret: YXA6J52gG77BGu85t6xvRKlW5xqeJAs
    imp-lib: httpclient
    default-owner: d4f5056b744d4553882a90bd93179ac2
    saltpass: meiyePass
    appkey: meiye
jpush:
    apns-production: true
    key: 5c13c997447a0d8058461fc1
    secret: a8f591d00597ce26f414db12
pingpp:
    api-key: sk_test_iDyrrTXbPmTC1GuPmH4eD4KK
    app-id: app_fjPC8Su5SaL0nLij
    success_url: http://119.37.198.9:8910/sr/sa/pingpp/callBack
    body: "慧聘"
sc:
    access-key: ZuD8uQMh9_8qoX3ptf60eSB-ykT3JY0MoPc6l4SR
    secret-key: 3YaBslMBXvlUboU4WGnWSZrWmX1eu0xCABW3iGy2
breach:
    scale: 0.003
    min-breach: 10
